### ISSUE TITLE
[feature request] updateTree

### ISSUE THREAD

**Issue by rhalbersma** [stla/jsTreeR#12]
Could we get a new function `updateTree`? I'm using `{jsTreeR}` in an application with over a 1,000 leaf nodes and destroying the tree and re-rendering it gives severe flickering and sometimes 0.5 seconds of a white screen. Competing packages do the same: `{shinyTree}` has `updateTree` and `{shinyWidgets}` has `updateTreeInput` for better performance.

**Comment by stla** [comment]
Hi,

I will take a look at the **shinyTree** implementation, because I don't see how to do.

How is the **shinyWidgets** tree? Nice?

Thanks for the report.

**Comment by stla** [comment]
Hi @rhalbersma 

I've done the implementation. To install:

```r
remotes::install_github("stla/jsTreeR@updateJsTree")
```

And the new function is `jstreeUpdate`. 

Please give feedback.

**Comment by rhalbersma** [comment]
Thank you very much! That was amazingly quick! Looking at the source it is a surprisingly tiny amount code.

**Comment by LennyyGH** [comment]
Hi @stla ,

I have tested the jstreeUpdate function and it seems to be working well. However, in my real world application I am using an onRender function after the initialization of the tree, comparable to in jstreeExample("filtering"). This onRender functionality seems to be lost after using jstreeUpdate. Do you have a suggestion to use an onRender function combined with jstreeUpdate?

For example, I would like to use jstreeUpdate to select some nodes in the tree based on another input widget, and still use onRender logic afterwards to hide (other) specific nodes.

Many thanks for a nice package nonetheless!

**Comment by stla** [comment]
No idea, sorry.
