### ISSUE TITLE
jstreeOutput is not re-rendered in shiny

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#13]
When creating a `jstree` with reactive dependency regarding its nodes it isn't re-rendered in shiny.

We can see that the new object is generated  (message: `Populating tree using a list.`) and we can print it after a `browser()` call, however the shiny UI doesn't change.

Expected output when typing "Test":

![image](https://user-images.githubusercontent.com/36849480/226923228-f5e13daf-f876-4b1d-bc48-be3b9b833cbc.png)

Please see the following example:

```
library(jsTreeR)
library(shiny)

ui <- fluidPage(
  textInput("test", "test"),
  jstreeOutput("mytree")
)

server <- function(input, output, session){
  output[["mytree"]] <- renderJstree({
    nodes <- list(
      list(
        text = paste0(input$test, "Branch 1"),
        state = list(opened = TRUE, disabled = FALSE),
        type = "parent",
        children = list(
          list(text = "Leaf A", type = "child"),
          list(text = "Leaf B", type = "child"),
          list(text = "Leaf C", type = "child"),
          list(text = "Leaf D", type = "child")
        )
      ),
      list(text = "Branch 2", type = "parent", state = list(opened = TRUE))
    )
    # browser()
    jstree(nodes)
  })
}  

shinyApp(ui, server)
```

![nok](https://user-images.githubusercontent.com/36849480/226924254-e7356b63-de37-4b52-8243-844aa93f386a.gif)

PS: I've seen `jstreeUpdate` - however, I think completely re-rendering the widget should also be possible.

**Comment by stla** [comment]
In fact, now I vaguely remember that `jstreeDestroy` was introduced for this purpose. But `jstreeUpdate` is better if you just want to update the nodes.

**Comment by ismirsehregal** [comment]
Thanks Stéphane - For my "real world problem" I'm already using `jstreeUpdate`. I just thought the current behaviour might be unexpected for other shiny users. Most of them use renderXXX functions rather than (the more performant) updateXXX counterparts.

**Comment by stla** [comment]
Did you try with the **shinyTree** package?

**Comment by ismirsehregal** [comment]
{shinyTree} is not flexible enough regarding its configuration possibilities - I prefer your package :-).

**Comment by ismirsehregal** [comment]
A major difference seems to be that `shinyTree::renderTree` calls `shinyTree::updateTree` while `jsTreeR::renderJstree` calls `shinyRenderWidget`.

**Comment by stla** [comment]
It works now.
