### ISSUE TITLE
input[["mytree_full"]] is not updated on expanding a node

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#16]
I'd like to save the state of a jstree, so the user has the possibility to come back later and continue to work on it.

Currently the full input state (e.g. input[["mytree_full"]]) is not updated on expanding a node. However, it is updated when adding a child node via the contextMenu:

```
library(jsTreeR)
library(shiny)

ui <- fluidPage(
  textInput("test", "test"),
  jstreeOutput("mytree"),
  textOutput("opened")
)

server <- function(input, output, session){
  output[["mytree"]] <- renderJstree({
    # jstreeDestroy(session, id = "mytree")
    nodes <- list(
      list(
        text = paste0(input$test, "Branch 1"),
        state = list(opened = TRUE, disabled = FALSE),
        type = "parent",
        children = list(
          list(text = "Leaf A", type = "child"),
          list(text = "Leaf B", type = "child"),
          list(text = "Leaf C", type = "child"),
          list(text = "Leaf D", type = "child")
        )
      ),
      list(text = "Branch 2", type = "parent", state = list(opened = TRUE))
    )
    jstree(nodes, contextMenu = TRUE)
  })
  
  output$opened <- renderText({
    if(isTruthy(input[["mytree_full"]])){
      paste("Is node 1 opened?:", input[["mytree_full"]][[1]]$state$opened)
    }
  })
}  

shinyApp(ui, server)
```
![screen](https://github.com/stla/jsTreeR/assets/36849480/a8896147-9394-4f05-a859-a2f0dc4f626b)

**Comment by stla** [comment]
Hmm I didn't deal with this package for a while, it will be hard to fix. And maybe it's a bug from the JS library.

**Comment by stla** [comment]
I've upgrader the JS library but nothing changes. In fact, it seems that the `input[["mytree_full]]` doesn't react at all.

**Comment by stla** [comment]
Ok it works now, I had to add some events.

Could you try  `remotes::install_github("stla/jsTreeR@v3.3.16`?

**Comment by ismirsehregal** [comment]
Thanks for the swift investigation Stéphane, works perfectly!
