### ISSUE TITLE
overlapping nodes

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#17]
I guess this is an issue with the underlying js library, however, coming from [here](https://stackoverflow.com/questions/77313835/jstreer-bug-and-how-to-use-it-as-an-input-in-shiny):

Using the below hierarchy in some cases nodes are overlapping after being opened:

![screen](https://github.com/stla/jsTreeR/assets/36849480/9a50d119-00e9-4f77-9f22-988fc67b5dd7)

```
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    type = "root",
    children = list(
      list(
        text = "ChildA1",
        type = "child",
        children = list(list(text = "ChildA12",
                             type = "child"))
      ),
      list(text = "ChildA2",
           type = "child")
    )
  ),
  list(
    text = "RootB",
    type = "root",
    children = list(
      list(text = "ChildB1",
           type = "child"),
      list(text = "ChildB2",
           type = "child")
    )
  )
)

types <- list(root = list(icon = FALSE),
              child = list(icon = FALSE))

jstree(nodes,
       types = types,
       checkboxes = TRUE)
```

**Comment by stla** [comment]
Very strange, I never saw that. Could it be due to my recent update of the JS library?..

**Comment by akshaybholee** [comment]
I have tried it with Shiny. It works well with Shiny. When you try it standalone we see this bug.

**Comment by stla** [comment]
This is fixed, there was an error in the code. To install the version with the fix:

```r
remotes::install_github("stla/jsTreeR@tieSelection)
```

**Comment by ismirsehregal** [comment]
I can confirm - this is fixed.
