### ISSUE TITLE
FR: tie_selection setting

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#18]
I'd like to try using the [tie_selection](https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.tie_selection) setting for the checkbox plugin as shown [here](https://stackoverflow.com/a/33781673/9841389). Currently the `checkboxes` argument for `jstree()` is  logical.

I tried using `htmlwidgets::onRender` to set it, however, the behaviour doesn't change. The checkbox is still checked/unchecked once the text is clicked:

```
library(shiny)
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    children = list(
      list(
        text = "ChildA1"
      ),
      list(
        text = "ChildA2"
      )
    )
  ),
  list(
    text = "RootB",
    children = list(
      list(
        text = "ChildB1"
      ),
      list(
        text = "ChildB2"
      )
    )
  )
)

ui <- fluidPage(
  jstreeOutput("myTree")
)

server <- function(input, output, session){
  output[["myTree"]] <- renderJstree({
    suppressMessages(
      jstree(
        nodes,
        checkboxes=TRUE,
        dragAndDrop = TRUE
      ) |> htmlwidgets::onRender("function(el) {console.log(el); $(el).jstree({checkbox : { tie_selection : false }}); console.log(el);}"))
  })
}  

shinyApp(ui, server)
```

**Comment by stla** [comment]
Hi @ismirsehregal ,

Do you rather mean the [whole_node](https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.whole_node) option? (*a boolean indicating if clicking anywhere on the node should act as clicking on the checkbox*). I've just tried `tie_selection` and that does nothing, I don't understand what it is supposed to do. Going to try `whole_node`.

**Comment by stla** [comment]
Ok, this seems to work by setting both these options to `false`. Can you try?

```r
remotes::install_github("stla/jsTreeR@tieSelection)
```

**Comment by ismirsehregal** [comment]
I'll check it, thanks!

**Comment by ismirsehregal** [comment]
> Hi @ismirsehregal ,
> 
> Do you rather mean the [whole_node](https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.whole_node) option? (_a boolean indicating if clicking anywhere on the node should act as clicking on the checkbox_). I've just tried `tie_selection` and that does nothing, I don't understand what it is supposed to do. Going to try `whole_node`.

By default (tie_selection: true) sleceting a node (blue background) also checks / unchecks the checkbox. The purpose of setting tie_selection: false is to distinguish a click on the checkbox from a click on the node text. The problem I have is, that I would like to avoid changing the checkbox state to allow nodes to be dragged and dropped to another position.

This is the case with your `jsTreeR@tieSelection` branch, however, with `whole_node : false` I can no longer drag and drop multiple nodes at once. Are you sure only setting `tie_selection: false` has no effect?

Thanks for your time!

**Comment by ismirsehregal** [comment]
I just saw it does work to dnd multiple nodes (via shift or ctrl) when setting `dragAndDrop = TRUE` only the blue background (selection) is missing.

**Comment by ismirsehregal** [comment]
> [whole_node](https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.whole_node) o

I think you are right - the whole_node options seems to be what I want. So mybe we can leave tie_selection default.

**Comment by stla** [comment]
No, if I put `whole_node: false` and `tie_selection: true`, that does not work as expected, that is strange.

**Comment by stla** [comment]
Look, this is exactly what I'm saying: https://github.com/vakata/jstree/issues/2518

**Comment by stla** [comment]
This works:
```r
      jstree(
        nodes,
        checkboxes = TRUE,
        tieSelection = FALSE,
        dragAndDrop = TRUE
      )
```
What is the problem eventually?

**Comment by ismirsehregal** [comment]
Yes I forgot `dragAndDrop = TRUE` in my example - sorry about that.

So in the end your jsTreeR@tieSelection branch works as I requested. The only thing missing is the blue background to indicate which nodes are currently selected.

This: https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.keep_selected_style
is true (default) right?

**Comment by ismirsehregal** [comment]
Of course we can add some custom css. Would be great if you merge this branch. This works as expected:

```
library(shiny)
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    children = list(
      list(
        text = "ChildA1"
      ),
      list(
        text = "ChildA2"
      )
    )
  ),
  list(
    text = "RootB",
    children = list(
      list(
        text = "ChildB1"
      ),
      list(
        text = "ChildB2"
      )
    )
  )
)

ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .jstree-clicked {
        background-color: #337ab7 !important;
      }"))
  ),
  jstreeOutput("myTree")
)

server <- function(input, output, session){
  output[["myTree"]] <- renderJstree({
    suppressMessages(
      jstree(
        nodes,
        checkboxes = TRUE,
        tieSelection = FALSE,
        dragAndDrop = TRUE
      )
    )
  })
}  

shinyApp(ui, server)
```

**Comment by stla** [comment]
I have `keep_selected_style: false` in my code, but I don't remember why. I'm going to investigate.

**Comment by ismirsehregal** [comment]
I just realized that input$myTree_selected is no longer populated when using `tie_selection: false`.

**Comment by stla** [comment]
Argh!!

I've tried `keep_selected_style: true` but that does not change anything. I think one has **selected = checked** so that is normal.

**Comment by ismirsehregal** [comment]
Mhm - too bad. Would have been great to have a way to handle them separately. Text selection for drag and drop (modifying the hierarchy) and the checkbox state for filtering a dataset. Maybe I'll implement a mode to switch between checkbox TRUE/FALSE then.

**Comment by stla** [comment]
I've checked. With `tieSelection=FALSE`, the `select_node` event is triggered when one clicks on the text (however there's no color), but not when one checks the checkbox... Indeed, maybe one needs a `input$myTree_checked`...

**Comment by stla** [comment]
Just took a look at the doc. There's a `check_node ` event triggered when `tie_selection: false` and one checks a checkbox. So I think I can trigger the `select_node` event when this event `check_node` is triggered. What do you think?

**Comment by ismirsehregal** [comment]
So you would pass the checkbox state instead of the text selection `input$myTree_selected`?

**Comment by stla** [comment]
That would be the same, yes.

I4m fearing something: when dragging a node, it is automatically selected then?

**Comment by ismirsehregal** [comment]
No, if you left-click and hold it's not selected. Only if you left-click and release.

**Comment by ismirsehregal** [comment]
> So you would pass the checkbox state instead of the text selection to `input$myTree_selected`?

For my purposes this would be sufficient. I'm not interested in the user selecting a text as I can extract the hierarchy (and changes to it) via input$myTree or input$myTree_full. However, the checkbox state is needed for filtering via input$myTree_selected / input$myTree_selected_paths.

**Comment by stla** [comment]
I've just pushed an update. Now a node is selected when checking a checkbox.

But there's still a problem: when clicking on the text, this selects the node and *this deselects the other previously selected nodes*. 

Pfff :-(

**Comment by ismirsehregal** [comment]
Thanks! I'll have a look.

**Comment by ismirsehregal** [comment]
I just tested it. For me the deselection by clicking a text (without holding ctrl) ist not a problem. However, the data in `input$myTree_selected` still corresponds to the selected text - not the checked checkboxes (which is, what I would need).

**Comment by stla** [comment]
This is not what I observed. If you check some checkboxes, the nodes are in `$myTree_selected`. But then if you click a text, this destroys everything.

**Comment by ismirsehregal** [comment]
After launching the app, if you click on a text without hitting the checkbox `myTree_selected` should not change, but it does.

**Comment by stla** [comment]
I think I'm close to a solution. Wait.

**Comment by stla** [comment]
Nope, does not work.

Now I think the way to go is your first idea: `input$myTree_checked`.

And you won't believe it but I already did that! I don't remember why. Try `input$myTree_selected_tree`.

**Comment by stla** [comment]
Not sure but that's possible!

There's a difference though between `myTree_selected` and `myTree_selected_tree`: the second one also provides the parents of the selected nodes, it is a tree.

Should I rename it `myTree_checked`? Also I don't like "`tieSelection`"...

**Comment by ismirsehregal** [comment]
Above and beyond.. I can confirm `input$myTree_selected_tree` combined with the whole_node option works as expected.

Maybe `myTree_checked` and `myTree_checked_paths` to keep it aligned?

I had the same thought about `tieSelection`.. thinking about something better.

**Comment by stla** [comment]
I don't know yet. `checkFromText` or something like that?

**Comment by ismirsehregal** [comment]
I just saw, that the changes were already merged into the master branch - works great, thank you!

I'm wondering if it would be possible to add inputs `ID_checked` and `ID_checked_paths` as drop-in replacements for `ID_selected` and `ID_selected_paths` providing the same data structure. I'm struggeling to extract this from `ID_checked_tree`.

**Comment by stla** [comment]
Do you think I don't struggle? ^^

I will see, I'm afraid this is not easy. Because I think **jsTree** does not provide the same utilities for 'selected' and for 'checked'. In addition I don't easily understand my own code. But I'll try.

**Comment by ismirsehregal** [comment]
Ok I understand  😅.. I thought, maybe you've got a function ready on th JS side. Thanks for having a look!

**Comment by stla** [comment]
Nnooo, finally it was easy! There *is* a similar utility for 'selected' and 'checked', so I just took my code for 'selected' and copied it without the need to understand. Can you give a try please?
```r
remotes::install_github("stla/jsTreeR@checkedNodes")
```

**Comment by ismirsehregal** [comment]
This is perfect! Thank you Stéphane!

```
library(shiny)
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    children = list(
      list(
        text = "ChildA1"
      ),
      list(
        text = "ChildA2"
      )
    )
  ),
  list(
    text = "RootB",
    children = list(
      list(
        text = "ChildB1"
      ),
      list(
        text = "ChildB2"
      )
    )
  )
)

ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .jstree-clicked {
        background-color: #beebff !important;
      }"))
  ),
  jstreeOutput("myTree"),
  column(6, verbatimTextOutput("result_myTree_selected")),
  column(6, verbatimTextOutput("result_myTree_checked")),
  column(6, verbatimTextOutput("result_myTree_selected_paths")),
  column(6, verbatimTextOutput("result_myTree_checked_paths"))
)

server <- function(input, output, session){
  output[["myTree"]] <- renderJstree({
    suppressMessages(
      jstree(
        nodes,
        checkboxes = TRUE,
        checkWithText = FALSE,
        dragAndDrop = TRUE
      )
    )
  })
  
  output$result_myTree_selected <- renderPrint({
    input$myTree_selected
  })
  
  output$result_myTree_checked <- renderPrint({
    input$myTree_checked
  })
  
  output$result_myTree_selected_paths <- renderPrint({
    input$myTree_selected_paths
  })
  
  output$result_myTree_checked_paths <- renderPrint({
    input$myTree_checked_paths
  })
  
}  

shinyApp(ui, server)
```

**Comment by ismirsehregal** [comment]
I just read the NEWS:

> In fact, the selected nodes strangely behave when
> `{checkWithText=FALSE}`, they are not usable.

Why is that? When selecting multiple nodes via ctrl.+left click worh my above example (as done [here](https://github.com/stla/jsTreeR/issues/18#issuecomment-1772393595), everything seems finde?

**Comment by stla** [comment]
I don't know :-) Do you mean the *checked* nodes?

**Comment by stla** [comment]
Ah I've just seen the GIF you mention... hhmmm

**Comment by stla** [comment]
But that's very annoying there's no color.

I added a Shiny example in the package for `checkWithText`, I will add the drag-and-drop to this example.

**Comment by ismirsehregal** [comment]
> I don't know :-) Do you mean the _checked_ nodes?

I'm talking about thevselected node texts (via ctrl. or shift). The resulting data corresponds to the selection. I'll add another gif Laterne (currently on mobile).

**Comment by stla** [comment]
You know how to use jstree better than me!

**Comment by ismirsehregal** [comment]
It's pretty intuitive. We can select multiple nodes (or node texts) just like we can select files or folders in e.g. Windows Explorer.

**Comment by stla** [comment]
Yes but we don't see the selection. I'm currently trying
```r
css <- "
.jstree-clicked:not(.jstree-checked)  {
  background-color: tomato !important;
}"
```
That seems nice so far.

**Comment by stla** [comment]
Ok I improved the example. You're right, this is intuitive. `jstreeExample("checkWithText")` if you want to try it.

**Comment by ismirsehregal** [comment]
The example is nice! We could set `dragAndDrop = TRUE` as this in my eyes is the most important usecase to set `checkWithText = FALSE`. Hoever, If you would like to focus on the difference between `checkWithText = TRUE/FALSE` it is fine like this.

**Comment by stla** [comment]
But there is `dragAndDrop=TRUE`. This is even written in the title. Or maybe you have an old version, I still pushed some commits...

**Comment by ismirsehregal** [comment]
I'm getting:

```
> remotes::install_github("stla/jsTreeR@checkedNodes")
Skipping install of 'jsTreeR' from a github remote, the SHA1 (d2161a5f) has not changed since last install.
  Use `force = TRUE` to force installation
```

server code is:

```
shinyServer(
  function(input, output, session){

    output[["tree1"]] <- renderJstree({
      jstree(nodes, checkboxes = TRUE)
    })

    output[["tree2"]] <- renderJstree({
      jstree(nodes, checkboxes = TRUE, checkWithText = FALSE)
    })

  }
)
```

which defaults to `dragAndDrop = FALSE`

**Comment by stla** [comment]
Ah but I merged to master.

**Comment by ismirsehregal** [comment]
I just re-installed the master. Works fine!
However, I'd prefer only using `background-color: #beebff` (default color when `checkboxes = FLASE`). In my eyes red indicates there is something going wrong.

**Comment by stla** [comment]
Ok but I prefer a color *name*, because the user does not necessarily know what is the color `#beebff`.

**Comment by stla** [comment]
Wow, Github has printed a bullet with the color!!

**Comment by ismirsehregal** [comment]
Sorry - I missed that this is only implemented for the example.

**Comment by ismirsehregal** [comment]
Btw. it might be worth mentioning in the help, that once we use `checkWithText = FALSE` we need to use `checked = TRUE` instead of  `selected = TRUE` to pre-check a checkbox via the `state` parameter:

`state = list(loaded = TRUE, opened = TRUE, selected = FALSE, checked = TRUE, disabled = FALSE),`
