### ISSUE TITLE
Search does not show childs

### ISSUE THREAD

**Issue by algo-se** [stla/jsTreeR#2]
Hi, in shinyTree when you search for something it shows the childs of a node matching the search:
![shinytree](https://user-images.githubusercontent.com/72490678/107643155-12a9f100-6c76-11eb-9d96-ce64d25e4737.gif)

But as far as I can see when jsTreeR does not:
![jsTreeR](https://user-images.githubusercontent.com/72490678/107643586-a1b70900-6c76-11eb-8aa3-650946dd4762.gif)

**Comment by stla** [comment]
Hi,

 Maybe try with these options:

```
jstree(nodes, search = list(
  show_only_matches = TRUE,
  show_only_matches_children = TRUE
))
```

**Comment by algo-se** [comment]
Yeah, `show_only_matches_children = TRUE` was the key. Thanks! Awesome package!
