### ISSUE TITLE
Pass undetermined state to input$treeID_full

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#24]
Currently I cannot extract the third state of a checkbox:

![image](https://github.com/stla/jsTreeR/assets/36849480/c5faa054-7a10-45b7-8d96-5e946955d1f4)

In this state (some childs selected, others not) selected or checked are `FALSE` by default.

As far as I understand this state is called _undetermined_, as shown [here](https://stackoverflow.com/questions/19162186/set-jstree-node-to-undetermined-state/23850086#23850086):
![image](https://github.com/stla/jsTreeR/assets/36849480/1b511f5a-1f82-4135-bf8e-b6b8a2f770d9)

I tried to access it, but it doesn't seem to change:

```
library(jsTreeR)
library(shiny)
library(jsonlite)

nodes <- list(
  list(
    text = "Branch 1",
    state = list(
      opened = TRUE,
      disabled = FALSE,
      selected = FALSE,
      undetermined = TRUE
    ),
    type = "parent",
    children = list(
      list(
        text = "Leaf A",
        state = list(
          opened = TRUE,
          disabled = FALSE,
          selected = FALSE,
          checked = FALSE,
          undetermined = FALSE
        ),
        type = "child"
      ),
      list(
        text = "Leaf B",
        state = list(
          opened = TRUE,
          disabled = FALSE,
          selected = FALSE,
          checked = FALSE,
          undetermined = FALSE
        ),
        type = "child"
      ),
      list(
        text = "Leaf C",
        state = list(
          opened = TRUE,
          disabled = FALSE,
          selected = FALSE,
          checked = TRUE,
          undetermined = FALSE
        ),
        type = "child"
      ),
      list(
        text = "Leaf D",
        state = list(
          opened = TRUE,
          disabled = FALSE,
          selected = FALSE,
          checked = TRUE,
          undetermined = FALSE
        ),
        type = "child"
      )
    )
  ),
  list(
    text = "Branch 2",
    type = "parent",
    state = list(
      opened = TRUE,
      disabled = FALSE,
      selected = FALSE,
      checked = TRUE,
      undetermined = FALSE
    )
  )
)

ui <- fluidPage(jstreeOutput("mytree"),  verbatimTextOutput("mytree_full"))

server <- function(input, output, session) {
  output[["mytree"]] <- renderJstree({
    jstree(nodes, contextMenu = TRUE, checkboxes = TRUE, checkWithText = FALSE)
  })
  
  output$mytree_full <-  renderPrint({toJSON(input$mytree_full, pretty = TRUE)})
}



shinyApp(ui, server)
```

**Comment by stla** [comment]
Hi,

To get the "full" tree in Shiny, I just do:
```js
  Shiny.setInputValue(
    instance.element.attr("id") + "_full:jsTreeR.list",
    instance.get_json()
  );
```
So that means that this state is not included  in `get_json` by the JavaScript library.

**Comment by stla** [comment]
But one can get the undetermined states.

It would be nice to have `NA` for `checked`, no? What is your advice?

But there's no `NA` corresponding value  in JavaScript. We could have `NULL` maybe, and change `NULL` to `NA` in R.

**Comment by stla** [comment]
> So that means that this state is not included in get_json by the JavaScript library.

Should we open an issue on the **jstree** repo? This looks like an omission.

**Comment by ismirsehregal** [comment]
Hi Stéphane, thanks for looking into this. Sure let's ask. Maybe we've overlooked something.

**Comment by stla** [comment]
Ok, maybe I can loop over the tree and use `is_undetermined`. Not sur because I don't remember many things... Will see.

**Comment by stla** [comment]
Done 👍. On master.

**Comment by ismirsehregal** [comment]
Works perfectly! Thanks once again!
