### ISSUE TITLE
FR: modify jstree config (core.expand_selected_onload)

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#27]
I'd like to set `core.expand_selected_onload` to `false` as discussed [here](https://github.com/vakata/jstree/issues/921#issuecomment-66298193). Is there a "official" way to do this via `library(jsTreeR)`?

**Comment by stla** [comment]
Hi @ismirsehregal 
Why did you close? Currently there's no way, I think.

**Comment by ismirsehregal** [comment]
I wanted to realize a collapsed, but selected tree an thought a selection initially causes the tree to expand. However, this behaviour was caused by a misconfiguration. Actually it does what is expected (see below example).

For the future: If I'd like to try options like this, can this be injected via `htmlwidgets::onRender`? Otherwise it might make sense to allow the user passing a list of options. What do you think?

```
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    state = list(loaded = TRUE, opened = FALSE, selected = TRUE, undetermined = FALSE),
    type = "root",
    children = list(
      list(
        text = "ChildA1",
        state = list(loaded = TRUE, opened = TRUE, selected = TRUE, undetermined = FALSE),
        type = "child",
        children = list(list(text = "ChildA12",
                             state = list(loaded = TRUE, opened = TRUE, selected = TRUE, undetermined = FALSE),
                             type = "child"))
      ),
      list(text = "ChildA2",
           state = list(loaded = TRUE, opened = TRUE, selected = TRUE, undetermined = FALSE),
           type = "child")
    )
  ),
  list(
    text = "RootB",
    state = list(loaded = TRUE, opened = FALSE, selected = TRUE, undetermined = FALSE),
    type = "root",
    children = list(
      list(text = "ChildB1",
           state = list(loaded = TRUE, opened = TRUE, selected = TRUE, undetermined = FALSE),
           type = "child"),
      list(text = "ChildB2",
           state = list(loaded = TRUE, opened = TRUE, selected = TRUE, undetermined = FALSE),
           type = "child")
    )
  )
)

types <- list(root = list(icon = FALSE), child = list(icon = FALSE))

jstree(nodes,
       types = types,
       checkboxes = TRUE)

```

**Comment by stla** [comment]
I think this is not possible with `htmlwidgets::onRender`, because the options are applied when one initializes the tree.

Indeed, one could allow the user to pass a list of options. Then in the JS one would do:
```js
options.core = {
          data: x.data,
          multiple: x.multiple,
          check_callback: x.checkCallback,
          themes: {
            name: x.theme,
            icons: true,
            dots: true,
            responsive: false
          }
};
$.extend(options.core, x.options);
```
But this would require that the user knows exactly what he does.

**Comment by ismirsehregal** [comment]
I think this would be a good option as long as we keep the current defaults and mark the parameter as "advanced" in the description.

**Comment by stla** [comment]
Hi @ismirsehregal 
I added an argument `coreOptions`. This is on master.
```r
jstree(nodes,
       types = types,
       checkboxes = TRUE,
       coreOptions = list(expand_selected_onload = FALSE)
)
```

**Comment by ismirsehregal** [comment]
Great - thanks Stéphane!
