### ISSUE TITLE
Get selected nodes

### ISSUE THREAD

**Issue by lefkiospaikousis** [stla/jsTreeR#3]
Hi!

Is there a way to extract the selected nodes of the tree?
[similar to shinyTree::get_selected()]

Thanks

**Comment by stla** [comment]
Hi,

  Yes. If the outputID of your tree is `treeid` then the selected nodes are in `input$treeid_selected`. Note that you also get the parent nodes, and you have to filter if you want only the leaves. See [this example](https://stackoverflow.com/a/67301446/1100107).

**Comment by lefkiospaikousis** [comment]
Thanks! 
Great package

**Comment by stla** [comment]
@lefkiospaikousis With the new version (not on CRAN yet, but soon hopefully), you don't need to filter anymore if you want only the leaves. There's an option `selectLeavesOnly = TRUE` in the `jstree` function.
