### ISSUE TITLE
How to edit the contextMenu in the jstree?

### ISSUE THREAD

**Issue by lmeninato** [stla/jsTreeR#4]
```
library(jsTreeR)

nodes <- list(
  list(
    text = "RootA",
    type = "root",
    children = list(
      list(
        text = "ChildA1",
        type = "child"
      ),
      list(
        text = "ChildA2",
        type = "child"
      )
    )
  ),
  list(
    text = "RootB",
    type = "root",
    children = list(
      list(
        text = "ChildB1",
        type = "child"
      ),
      list(
        text = "ChildB2",
        type = "child"
      )
    )
  )
)

nodes %>% jstree(contextMenu = TRUE)
```

I tried: 

```
nodes %>% jstree(contextMenu = list(Rename = TRUE))
```

But this won't work. I assume you need to pass in the javascript for the corresponding callBack function? Is there any documentation how how to pass this information through? Ideally I could just have the callback function loaded in an external js script. 

Thanks again for building this widget. Fits my use case perfectly, and shinyTree wasn't working well.

**Comment by stla** [comment]
Good question, I think I never tried... I will try now.

**Comment by stla** [comment]
There's an example in the `folderGadget`: https://github.com/stla/jsTreeR/blob/master/R/folderGadget.R
I don't remember how I did that, that does not seem very easy.

**Comment by stla** [comment]
See also <https://github.com/stla/jsTreeR/blob/master/inst/htmlwidgets/gadget/gadget.js>.

**Comment by stla** [comment]
Ah, this works like this:

`jstree(nodes, checkCallback = TRUE, contextMenu = list(rename = TRUE))`

**Comment by lmeninato** [comment]
I tried this:

```
... %>%
          jsTreeR::jstree(checkCallback = TRUE, contextMenu = list(rename = TRUE,
                                                                   delete = TRUE,
                                                                   create = TRUE))
```

and it still showed other items in the context menu?

**Comment by stla** [comment]
Sorry, maybe I will try tomorrow. I have to figure out how I did for the folder gadget.

**Comment by stla** [comment]
Do you use jstreeR in Shiny?

**Comment by stla** [comment]
I've found!

```
library(jsTreeR)

customMenu <- JS("function customMenu(node)
{
  var tree = $('#mytree').jstree(true);
  var items = {
    'rename' : {
      'label' : 'Rename',
      'action' : function (obj) { tree.edit(node); }
    },
    'item2' : {
      'label' : 'item2',
      'action' : function () { /* action */ }
    }
  }
  
  return items;
}")

nodes <- list(
  list(
    text = "RootA",
    type = "root",
    children = list(
      list(
        text = "ChildA1",
        type = "child"
      ),
      list(
        text = "ChildA2",
        type = "child"
      )
    )
  ),
  list(
    text = "RootB",
    type = "root",
    children = list(
      list(
        text = "ChildB1",
        type = "child"
      ),
      list(
        text = "ChildB2",
        type = "child"
      )
    )
  )
)

jstree(
  nodes, checkCallback = TRUE, elementId = "mytree",
  contextMenu = list(items = customMenu)
)
```

**Comment by stla** [comment]
And here for "delete" and "create":

```
library(jsTreeR)

customMenu <- JS("function customMenu(node)
{
  var tree = $('#mytree').jstree(true);
  var items = {
    'rename' : {
      'label' : 'Rename',
      'action' : function (obj) { tree.edit(node); }
    },
    'delete' : {
      'label' : 'Delete',
      'action' : function (obj) { tree.delete_node(node); }
    },
    'create' : {
      'label' : 'Create',
      'action' : function (obj) { tree.create_node(node); }
    }
  }
  return items;
}")

nodes <- list(
  list(
    text = "RootA",
    children = list(
      list(
        text = "ChildA1"
      ),
      list(
        text = "ChildA2"
      )
    )
  ),
  list(
    text = "RootB",
    children = list(
      list(
        text = "ChildB1"
      ),
      list(
        text = "ChildB2"
      )
    )
  )
)

jstree(
  nodes, checkCallback = TRUE, elementId = "mytree",
  contextMenu = list(items = customMenu)
)
```

**Comment by stla** [comment]
With icons:

```
customMenu <- JS("function customMenu(node)
{
  var tree = $('#mytree').jstree(true);
  var items = {
    'rename' : {
      'label' : 'Rename',
      'action' : function (obj) { tree.edit(node); },
      'icon': 'glyphicon glyphicon-edit'
    },
    'delete' : {
      'label' : 'Delete',
      'action' : function (obj) { tree.delete_node(node); },
      'icon' : 'glyphicon glyphicon-trash'
    },
    'create' : {
      'label' : 'Create',
      'action' : function (obj) { tree.create_node(node); },
      'icon': 'glyphicon glyphicon-plus'
    }
  }
  return items;
}")
```

**Comment by stla** [comment]
I close. Now this example is in the new CRAN version. Feel free to reopen if you have other questions.

**Comment by lmeninato** [comment]
Sorry for the late response! Got caught up with some other work... Thanks I'll give this a shot now.

**Comment by lmeninato** [comment]
Yep this is perfect 🥳! Thanks again.

For future reference if anyone sees we can trigger custom event handlers from javascript and then handle them in R by calling `Shiny.setInputValue("{shiny_input_id}", {...vals}, {priority: "event"})` from JS and then handling the event with an event handler from R: `observeEvent{input$shiny_input_id, { code to handle event .... })`.

**Comment by stla** [comment]
Yes, this is what I do in the folder gadget.
Cheers.

**Comment by lmeninato** [comment]
I can't do this on the latest version of jsTreeR btw.



> 
> 
> And here for "delete" and "create":
> 
> ```
> library(jsTreeR)
> 
> customMenu <- JS("function customMenu(node)
> {
>   var tree = $('#mytree').jstree(true);
>   var items = {
>     'rename' : {
>       'label' : 'Rename',
>       'action' : function (obj) { tree.edit(node); }
>     },
>     'delete' : {
>       'label' : 'Delete',
>       'action' : function (obj) { tree.delete_node(node); }
>     },
>     'create' : {
>       'label' : 'Create',
>       'action' : function (obj) { tree.create_node(node); }
>     }
>   }
>   return items;
> }")
> 
> nodes <- list(
>   list(
>     text = "RootA",
>     children = list(
>       list(
>         text = "ChildA1"
>       ),
>       list(
>         text = "ChildA2"
>       )
>     )
>   ),
>   list(
>     text = "RootB",
>     children = list(
>       list(
>         text = "ChildB1"
>       ),
>       list(
>         text = "ChildB2"
>       )
>     )
>   )
> )
> 
> jstree(
>   nodes, checkCallback = TRUE, elementId = "mytree",
>   contextMenu = list(items = customMenu)
> )
> ```

Not working on the latest version btw :(

**Comment by lmeninato** [comment]
https://github.com/stla/jsTreeR/issues/4#issuecomment-931492009

> 
> 
> I can't do this on the latest version of jsTreeR btw.
> 
> > And here for "delete" and "create":
> > ```
> > library(jsTreeR)
> > 
> > customMenu <- JS("function customMenu(node)
> > {
> >   var tree = $('#mytree').jstree(true);
> >   var items = {
> >     'rename' : {
> >       'label' : 'Rename',
> >       'action' : function (obj) { tree.edit(node); }
> >     },
> >     'delete' : {
> >       'label' : 'Delete',
> >       'action' : function (obj) { tree.delete_node(node); }
> >     },
> >     'create' : {
> >       'label' : 'Create',
> >       'action' : function (obj) { tree.create_node(node); }
> >     }
> >   }
> >   return items;
> > }")
> > 
> > nodes <- list(
> >   list(
> >     text = "RootA",
> >     children = list(
> >       list(
> >         text = "ChildA1"
> >       ),
> >       list(
> >         text = "ChildA2"
> >       )
> >     )
> >   ),
> >   list(
> >     text = "RootB",
> >     children = list(
> >       list(
> >         text = "ChildB1"
> >       ),
> >       list(
> >         text = "ChildB2"
> >       )
> >     )
> >   )
> > )
> > 
> > jstree(
> >   nodes, checkCallback = TRUE, elementId = "mytree",
> >   contextMenu = list(items = customMenu)
> > )
> > ```
> 
> Not working on the latest version btw :(

Never mind... some other dependency must clash with it in one of my projects, which causes the customMenu to not work! Very bizarre.

**Comment by lmeninato** [comment]
Ok not sure why it didnt work with htmlwidgets 1.5.2. Upgrading to 1.5.4 seemed to do the trick...
