### ISSUE TITLE
Lazy loading nodes no longer works.

### ISSUE THREAD

**Issue by bschulth** [stla/jsTreeR#5]
In v.1.2.0, we used to be able to pass an htmlwidgets::JS() object as the 'nodes' parameter to jsTreeR::jstree(node). 
This would allow us to setup AJAX remote node loading via callback function().

Now you have a check that forces 'nodes' to be a node list:

    https://github.com/stla/jsTreeR/blob/master/R/jstree.R#L381

and AJAX/lazy node loading via callback function is now broken:

https://github.com/vakata/jstree/wiki#populating-the-tree-using-a-callback-function

Is the "isNodesList()" critical for you, or can you remove that to re-enable ajax callbacks?
Or can you use your isJS() function and allow either:

if(!isNodesList(nodes) && !isJS(nodes)) {
  stop()
}

For reference, I implemented the AJAX callback using guidance from Dean Attali's notes here:

https://github.com/daattali/advanced-shiny/tree/master/api-ajax

**Comment by stla** [comment]
Hi @bschulth 

 I didn't know that. I've done some modifications, but not tested yet. Could you try

`remotes::install_github("stla/jsTreeR@ajax")`

**Comment by stla** [comment]
I did the tests now. This works.

```r
library(jsTreeR)

jstree(
  nodes = JS('
  function (node, cb) {
    if(node.id === "#") {
      cb([{"text" : "Root", "id" : "1", "children" : true}]);
    } else {
      cb(["Child"]);
    }
  }')
)


jstree( # does not work in RStudio viewer
  nodes = list(
    url = "https://www.jstree.com/fiddle/",
    dataType = "json"
  )
)


jstree( # does not work in RStudio viewer
  nodes = list(
    url = "https://www.jstree.com/fiddle/?lazy",
    data = JS('function(node){return { "id" : node.id };}')
  )
)
```

**Comment by stla** [comment]
Now it is on master, so you can do `remotes::install_github("stla/jsTreeR")`.
I would be glad if you showed me an example of what you do with this feature.

**Comment by bschulth** [comment]
Thanks!  I can confirm it works as expected now.

I put an an example up of how I use AJAX to lazily load tree nodes here:

https://github.com/bschulth/jsTreeRExample

**Comment by stla** [comment]
Thanks!
