### ISSUE TITLE
jstree update in shiny

### ISSUE THREAD

**Issue by PierreStevenin** [stla/jsTreeR#6]
I want to display a tree which updates each time I change the path.
Classic reactive code does not seem to work properly : the tree appears the first time I enter a path, but when I change the path, tree stay frozen.
I may miss something here
[tree.zip](https://github.com/stla/jsTreeR/files/7829972/tree.zip)
.

**Comment by stla** [comment]
Which path are you talking about? I don't understand your question.

**Comment by stla** [comment]
Ok, I looked at your zip. That looks better like this but that still doesn't update, I don't know why:

```
  fNodeWorkspace <- reactive({
    directory <- input$dirWorkspace
    req(dir.exists(directory))
    folder <- list.files(directory, recursive = TRUE)
    fMakeNodes(folder)
  })
```

**Comment by stla** [comment]
I've done it. You can proceed as follows:

```r
  fNodeWorkspace <- reactive({
    directory <- input$dirWorkspace
    req(dir.exists(directory))
    jstreeDestroy(session, "configWorkTree") # <--- new
    folder <- list.files(directory, recursive = TRUE)
    fMakeNodes(folder)
  })
  
  #show tree folder
  output$configWorkTree <- renderJstree({
    jstree(nodes = fNodeWorkspace(), sort = T, theme = "proton")
  })
```

You have to install the development version:

`remotes::install_github("stla/jsTreeR")`

**Comment by PierreStevenin** [comment]
It works perfectly.
Thanks!

**Comment by stla** [comment]
Cool. I gonna submit to CRAN.
